version: "3.6"

services:
  redis:
    image: redis:3.2.5

  web:
    image: ruby:2.6.3
    command:
      - /bin/bash
      - -c
      - |
        bundle install
        bundle exec rackup -o 0.0.0.0
    environment:
      - REDIS_SERVER_URL=redis://redis:6379/4
    ports:
      - "9292:9292"
    volumes:
      - .:/srv
    working_dir: /srv

  worker2.5:
    image: ruby:2.5.3
    command:
      - /bin/bash
      - -c
      - |
        bundle install
        bundle exec sidekiq -g ruby2.5.3 -r ./boot.rb -c 1
    environment:
      - REDIS_SERVER_URL=redis://redis:6379/4
    volumes:
      - .:/srv
    working_dir: /srv

  worker2.6:
    image: ruby:2.6.3
    command:
      - /bin/bash
      - -c
      - |
        bundle install
        bundle exec sidekiq -g ruby2.6.3 -r ./boot.rb -c 1
    environment:
      - REDIS_SERVER_URL=redis://redis:6379/4
    volumes:
      - .:/srv
    working_dir: /srv
